# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bitcoin Optech
email: info@bitcoinops.org

description: >-
  Helping Bitcoin-based businesses integrate scaling technology.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitcoinops.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bitcoinoptech
github_username:  bitcoinops
mastodon:
     - username: bitcoinoptech
       instance: x0f.org
repository_name: bitcoinops.github.io
bold: '**'
author: "Bitcoin Optech"  ## Default author name for blog posts

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/
   - Makefile
   - README.md
   - CONTRIBUTING.md

include: [".well-known"]

show_excerpts: true

defaults:
  - scope:
      path: ""  ## all pages
    values:
      image: https://bitcoinops.org/img/logos/optech-notext.png
      breadcrumbs: true
      localizable: true
  - scope:
      path: "_topics"
    values:
      layout: topic
      permalink: /en/topics/:title/
      localizable: false

collections:
  topics:
    output: true

languages:
  - code: ja
    name: Japanese
  - code: es
    name: Spanish
  - code: cs
    name: Czech
  - code: hi
    name: Hindi
  - code: zh
    name: Chinese
  - code: de
    name: German
  - code: fr
    name: French
## In-text aliases
trb: "709,632" # TapRoot Block (activation)
