#!/bin/bash -eu

TOPICS_DIR=_topics/en

if ! [ -d "$TOPICS_DIR" ]
then
  echo "Couldn't find $TOPICS_DIR.  Are you sure you're in the repository root directory?"
  exit 1
fi

echo -n "Name of new topic (capitalize first word): "
read
topic="$REPLY"
topic_lowercase=$( echo $topic | tr '[A-Z]' '[a-z]' )

file="$TOPICS_DIR/$( echo $topic_lowercase | sed 's/ /-/g' ).md"
if [ -f "$file" ]
then
  echo "$file already exists, no overwriting"
  exit 1
fi

cat <<EOF > $file
---
title: ${topic}

## Optional.  Shorter name to use for reference style links e.g., "foo"
## will allow using the link [topic foo][].  Not case sensitive
# shortname: foo

## Optional.  An entry will be added to the topics index for each alias
#aliases:
#  - Foo

## Required.  At least one category to which this topic belongs.  See
## schema for options
categories:
  - TODO

## Optional.  Produces a Markdown link with either "[title][]" or
## "[title](link)"
primary_sources:
    - title: Test
    - title: Example
      link: https://example.com

## Optional.  Each entry requires "title", "url", and "date".  May also use "feature:
## true" to bold entry
optech_mentions:
  - title: An example page
    url: /en/newsletters/2019/05/29/#news
    date: 1970-01-01

## Optional.  Same format as "primary_sources" above
# see_also:
#   - title:
#     link:

## Required.  Use Markdown formatting.  Only one paragraph.  No links allowed.
## Should be less than 500 characters
excerpt: >
  **${topic}** is ...
---
This is the summary that never ends.  It goes on and on, my friend.
Some people started writing it not knowing what it was but...

...they'll be writing it forever, because this is the summary that
never ends.  It goes on and on, my friend...

{% include references.md %}
{% include linkers/issues.md issues="" %}
EOF

echo $file
