@startditaa
                Public Information

        Block n                Mempool
+------+------+------+   +------+------+------+
| c000 | c111 | c222 |   | c111 | c222 | c666 |
+------+------+------+   +------+------+------+
| c333 | c444 | c555 |   | c888 | cAAA | cBBB |
+------+------+------+   +------+------+------+
| c666 | c777 | cCCC |   | cCCC | cDDD | cEEE |
+------+------+------+   +------+------+------+

------------------------------------------------

        Honest miner works on Block n+1
              using mempool txes

        Block n                Block n+1
+------+------+------+   +------+------+------+
| c000 | c111 | c222 |   | c111 | c222 | c666 |
+------+------+------+   +------+------+------+
| c333 | c444 | c555 |   | c888 | cAAA | cBBB |
+------+------+------+   +------+------+------+
| c666 | c777 | cCCC |   | cCCC | cDDD | cEEE |
+------+------+------+   +------+------+------+

------------------------------------------------

    Dishonest miner works to move high feerate
transactions from mempool into alternative block n'

          Block n'               Block n'+1
+------+------+------+   +------+------+------+
| c000 | c111 | c111 |   | c666 | c777 | c888 |
+------+------+------+   +------+------+------+
| c222 | c222 | c333 |   | cAAA | cBBB | cCCC |
+------+------+------+   +------+------+------+
| c444 | c555 | c666 |   | cCCC | cDDD | cEEE |
+------+------+------+   +------+------+------+
@endditaa
